# Generated by Django 4.2.1 on 2023-05-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview',
            field=models.ImageField(default=None, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
